all:
	lualatex doc

release:
	lualatex doc
	lualatex doc
	bibtex doc
	lualatex doc
	lualatex doc

clean:
	rm -f *.aux
	rm -f *.lof
	rm -f *.log
	rm -f *.lot
	rm -f *.fls
	rm -f *.out
	rm -f *.toc
	rm -f *.bbl
	rm -f *.bcf
	rm -f *.blg
	rm -f *.brf
	rm -f *.dvi
	rm -f *.pdf
