package cuttle.game.updates;

import org.json.JSONObject;

/**
 * Container for an update's JSONs, to be generated by classes which implement
 * UpdateInterface.
 */
public class UpdateContainer {
    public JSONObject playerUpdate() {
        return mPlayerUpdate;
    }

    public JSONObject opponentUpdate() {
        return mOpponentUpdate;
    }

    private JSONObject mPlayerUpdate;
    private JSONObject mOpponentUpdate;

    /**
     * Initializes the container with the player and the opponent's JSONs.
     *
     * @param playerUpdate JSON for the current player's update.
     * @param opponentUpdate JSON for the opponent's update.
     */
    public UpdateContainer(JSONObject playerUpdate, JSONObject opponentUpdate){
        mPlayerUpdate = playerUpdate;
        mOpponentUpdate = opponentUpdate;
    }

}
